package com.myspace.sample1;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Excel implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private int contEmployee;
	private int countDate;
	private int assingEmployee;
	private int assignDate;
	public java.util.List<java.lang.String> statusList;
	private java.lang.String emailBody;

	public java.util.List<java.lang.String> queryList;

	public Excel() {
	}

	public int getCountEmployee() {
		return this.contEmployee;
	}

	public void setCountEmployee(int contEmployee) {
		this.contEmployee = contEmployee;
	}

	public int getCountDate() {
		return this.countDate;
	}

	public void setCountDate(int countDate) {
		this.countDate = countDate;
	}

	public int getAssignEmployee() {
		return this.assingEmployee;
	}

	public void setAssignEmployee(int assingEmployee) {
		this.assingEmployee = assingEmployee;
	}

	public int getAssignDate() {
		return this.assignDate;
	}

	public void setAssignDate(int assignDate) {
		this.assignDate = assignDate;
	}

	public java.util.List<java.lang.String> getStatusList() {
		return this.statusList;
	}

	public void setStatusList(java.util.List<java.lang.String> statusList) {
		this.statusList = statusList;
	}

	public java.lang.String getEmailBody() {
		return this.emailBody;
	}

	public void setEmailBody(java.lang.String emailBody) {
		this.emailBody = emailBody;
	}

	public java.util.List<java.lang.String> getQueryList() {
		return this.queryList;
	}

	public void setQueryList(java.util.List<java.lang.String> queryList) {
		this.queryList = queryList;
	}

	public Excel(int contEmployee, int countDate, int assingEmployee,
			int assignDate, java.util.List<java.lang.String> statusList,
			java.lang.String emailBody,
			java.util.List<java.lang.String> queryList) {
		this.contEmployee = contEmployee;
		this.countDate = countDate;
		this.assingEmployee = assingEmployee;
		this.assignDate = assignDate;
		this.statusList = statusList;
		this.emailBody = emailBody;
		this.queryList = queryList;
	}

}