package com.myspace.sample1;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Leave implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String str;

	private java.lang.String str1;

	private int count1;

	private int count2;

	private boolean flag1;

	private boolean flag2;

	public Leave() {
	}

	public java.lang.String getStr() {
		return this.str;
	}

	public void setStr(java.lang.String str) {
		this.str = str;
	}

	public java.lang.String getStr1() {
		return this.str1;
	}

	public void setStr1(java.lang.String str1) {
		this.str1 = str1;
	}

	public int getCount1() {
		return this.count1;
	}

	public void setCount1(int count1) {
		this.count1 = count1;
	}

	public int getCount2() {
		return this.count2;
	}

	public void setCount2(int count2) {
		this.count2 = count2;
	}

	public boolean isFlag1() {
		return this.flag1;
	}

	public void setFlag1(boolean flag1) {
		this.flag1 = flag1;
	}

	public boolean isFlag2() {
		return this.flag2;
	}

	public void setFlag2(boolean flag2) {
		this.flag2 = flag2;
	}

	public Leave(java.lang.String str, java.lang.String str1, int count1,
			int count2, boolean flag1, boolean flag2) {
		this.str = str;
		this.str1 = str1;
		this.count1 = count1;
		this.count2 = count2;
		this.flag1 = flag1;
		this.flag2 = flag2;
	}

}